Updated mock rate limiter class with updated limits for LARGE_PRINT
ONSdigital/census-envoy-proxy-rate-limiter-cucumber pull request #5
Opened 2021-01-22 12:06 UTC by andrewjohnysons

Updated mock rate limiter class with updated limits for LARGE_PRINT fulfilments

LARGE_PRINT (INDIVIDUAL)=FALSE POST 5 HH uprn
LARGE_PRINT (INDIVIDUAL)=FALSE POST 5 SPG uprn
LARGE_PRINT (INDIVIDUAL)=TRUE POST 10 HH uprn
LARGE_PRINT (INDIVIDUAL)=TRUE POST 10 SPG uprn

2021-01-25 14:17 UTC, rpcatling requested changes
LARGE-PRINT-POST-HH.feature is empty.  Probably needs some feature tests in it.

2021-01-26 10:56 UTC, rpcatling approved these changes
couple of minor comments, but approved

2021-01-26 10:56 UTC, rpcatling commented on README.md
> +        LARGE-PRINT-POST-HH.feature
the markdown doesn't format as a list . Consider improving this so it formats nicely.

2021-01-26 10:56 UTC, rpcatling commented on src/test/resources/features/combotests/LARGE-PRINT-POST-HH.feature
> +      | 10            | 10             | 0              |"LARGE_PRINT"| "POST"          | "HH"       | "true"     | "0000000" | ".0.2.7"  | "901114" |
new line at the end please!

2021-01-26 10:56 UTC, rpcatling commented on src/test/resources/features/combotests/LARGE-PRINT-POST-SPG.feature
> +      | 60            | 50             | 10             |"LARGE_PRINT"| "POST"          | "CE"       | "true"     | "0000000" | ".0.2.2"  | "921114" |
new line at the end please

2021-01-26 10:59 UTC, andrewjohnysons commented on src/test/resources/features/combotests/LARGE-PRINT-POST-SPG.feature
> +      | 60            | 50             | 10             |"LARGE_PRINT"| "POST"          | "CE"       | "true"     | "0000000" | ".0.2.2"  | "921114" |
ha - ok

2021-01-26 11:04 UTC, andrewjohnysons commented on README.md
> +        LARGE-PRINT-POST-HH.feature
Updated the markdown

2021-01-27 12:52 UTC, philwhiles approved these changes

2021-01-27 12:52 UTC, merged